#ifndef __IMAGES__H
#define __IMAGES__H


/*EDDIE IMAGES*/
#define EDDIE_HAT_HEIGHT 2
#define EDDIE_HAT_WIDTH 10

#define EDDIE_BODY1_HEIGHT 3
#define EDDIE_BODY1_WIDTH 10

#define EDDIE_BODY2_HEIGHT 3
#define EDDIE_BODY2_WIDTH 10

#define EDDIE_BODY_MOVING_HEIGHT 3
#define EDDIE_BODY_MOVING_WIDTH 10

#define EDDIE_BODY_MOVING2_HEIGHT 3
#define EDDIE_BODY_MOVING2_WIDTH 10

#define EDDIE_SHIRT_HEIGHT 8
#define EDDIE_SHIRT_WIDTH 10

#define EDDIE_HEIGHT 16

/*SNEAKER IMAGES*/
#define  HEAD_HEIGHT 4
#define  HEAD_WIDTH 11

#define LEGS_HEIGHT 3
#define LEGS_WIDTH 11

#define LEGS_EXTRA_HEIGHT 1
#define LEGS_EXTRA_WIDTH 11


/*ITEM IMAGE*/
#define ITEM_HEIGHT 5
#define ITEM_WIDTH 7


/*LADDER IMAGE*/
#define LADDER_HEIGHT 21
#define LADDER_WIDTH 22


/*FLOOR IMAGE*/
#define FLOOR_WIDTH 128
#define FLOOR_HEIGHT 3

#endif